### ISSUE TITLE
Merge the two navigation menu in one

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board#1]
Actually you have two navigation menu : one on top left and one on bottom center. Please put the navigation menu on top left with the bottom center one.

The unique navigation menu in circle should be splitted in two buttons : one to draw, one to use widgets.

The "go back" / "cancel" / "save" buttons that we have at the left of the top left navigation menu can stay here (maybe more to the left...).

<img width="69" alt="screen shot 2016-05-30 at 14 00 55" src="https://cloud.githubusercontent.com/assets/5302702/15649058/f521b714-266e-11e6-8ed3-8b97e03b5495.png">

**Comment by CremaFR** [comment]
https://gyazo.com/ae16cbb2b06c41f52bb7c7227008c682

I've made some tests about the buttonMenu in my branch 'DevNewMenu'. Result shown above was kind of easy to make, but if we want the same visual output for widgets and drawing tools it will require a lot of refactors.

Because if you look at my work you will see that I replaced the widgetNavBar for Elements.js which is just an array of "button widget" without state, just a text, an icon and an action to fire on click. 
The problem with the drawing menu is that there is an internal state to show, for example, a color picker or the current value of line-height. My point is : I cannot extract all this navBarElement to a simple array in an external js file like I did for the widgets.

**Comment by CremaFR** [comment]
On branch TestDrawingNavBar I've made a refactor to move state logic from drawingNavBar.jsx to backgroundDrawing (Which was already listening to events fired by the NavBar).

This way I could create a js file with only pure JS elements and pass this as props to my buttonMenu, like I did for the widget Menu

But the problem is with  [staggered motion](https://github.com/chenglou/react-motion#staggeredmotion-) It says animated **fixed length** of elements and my few tries to modify the elements list to display were not successful :'(

**Comment by CremaFR** [comment]
Not wanted anymore I close
